version: '3.8'

networks:
  minio_network:
    external: true
  samarkand-notbuk:
    external: true

services:
  app:
    image: "${DOCKER_USERNAME}/${DOCKER_PROJECTNAME}:${DOCKER_TAG}"
    ports:
      - "127.0.0.1:8345:8345"
    restart: always
    logging:
      driver: "json-file"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./config/docker.yml:/app/config/docker.yml
      - ./api/docs/docs.go:/app/api/docs/docs.go
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - secret=${secret}
      - ENV=docker
    labels:
      - "app=samarkand-notbuk-server"
      - "service=samarkand-notbuk-server"
    networks:
      - minio_network
      - samarkand-notbuk

  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - samarkand-notbuk

  postgres:
    restart: always
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: samarkand_notbuk_sayt
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - samarkand-notbuk

volumes:
  postgres_data: