services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8345:8345"
    restart: always
    labels:
      logging: "promtail"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    restart: always
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: samarkand_notbuk_sayt
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: