server:
  host: "0.0.0.0"
  port: 8345
  public_host: "0.0.0.0:8345"

db:
  host: postgres
  port: 5432
  dbname: samarkand_notbuk_sayt
  sslmode: disable
  migrations: migrations

redis:
  host: redis
  port: 6379

filestorage:
  url: https://example.com

media:
  category_photo_max_size: 3  #mb

  product_photo_max_size:  3  #mb
  product_max_photo_count: 3  #mb
  product_max_video_count: 3  #mb
  product_video_max_size:  3  #mb