server:
  host: "0.0.0.0"
  port: 10000
  public_host: notbuk-seller-islombay.koyeb.app:8345

db:
  host: ep-late-shadow-a12pujze.ap-southeast-1.pg.koyeb.app
  port: 5432
  dbname: koyebdb
  sslmode: require
  migrations: migrations

redis:
  host: localhost
  port: 2345

filestorage:
  url: https://example.com

media:
  category_photo_max_size: 3  #mb

  product_photo_max_size:  3  #mb
  product_max_photo_count: 3  #mb
  product_max_video_count: 3  #mb
  product_video_max_size:  3  #mb