server:
  host: "0.0.0.0"
  port: 10000
  public_host: samarkand-notbuk.onrender.com

db:
  host: ep-late-shadow-a12pujze.ap-southeast-1.pg.koyeb.app
  port: 5432
  dbname: koyebdb
  sslmode: require
  migrations: migrations

redis:
  host: "red-cp3e81vsc6pc73fn8qfg"
  port: "6379"

filestorage:
  url: https://example.com

media:
  category_photo_max_size: 3  #mb

  product_photo_max_size:  3  #mb
  product_max_photo_count: 3  #mb
  product_max_video_count: 3  #mb
  product_video_max_size:  3  #mb