# name: CI/CD

# on:
#   push:
#     branches:
#       - deploy

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       DOCKER_TAG: ${{ github.sha }}
#       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#       DOCKER_PROJECTNAME: ${{ secrets.DOCKER_PROJECTNAME }}

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.21.4

#     - name: Build Docker image
#       run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROJECTNAME}}:${{ github.sha }} .

#     - name: Log in to Docker Hub
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#     - name: Push Docker image
#       run: docker push ${{ secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_PROJECTNAME}}:${{ github.sha }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Deploy to server
#       uses: appleboy/ssh-action@master
#       with:
        # host: ${{ secrets.SERVER_HOST }}
        # username: ${{ secrets.SERVER_USERNAME }}
        # key: ${{ secrets.SERVER_SSH_KEY }}
#         script: |
#           mkdir -p ~/islombay/go/web/samarkand-notbuk
#           cd ~/islombay/go/web/samarkand-notbuk

#           git pull origin deploy
#           git switch deploy

#           docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROJECTNAME }}:${{ github.sha }}
#           docker-compose down
#           docker-compose up -d

name: CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PROJECTNAME: ${{ secrets.DOCKER_PROJECTNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.4

    - name: Build Docker image
      run: docker build --no-cache -t $DOCKER_USERNAME/$DOCKER_PROJECTNAME:$DOCKER_TAG .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/$DOCKER_PROJECTNAME:$DOCKER_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/islombay/go/web/samarkand-notbuk
          cd ~/islombay/go/web/samarkand-notbuk

          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ DOCKER_PROJECTNAME }}:${{ github.sha }}
          echo "DOCKER_TAG=${{ github.sha }}" >> .env
          docker-compose down
          docker-compose up -d