name: CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PROJECTNAME: ${{ secrets.DOCKER_PROJECTNAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PWD: ${{ secrets.DB_PWD }}
      secret: ${{ secrets.secret }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROJECTNAME }}:${{ github.sha }} .

    - name: Test env
      run: echo $DOCKER_TAG

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/$DOCKER_PROJECTNAME:$DOCKER_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/islombay/go/web/samarkand-notbuk
          cd ~/islombay/go/web/samarkand-notbuk

          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROJECTNAME }}:${{ github.sha }}

          echo "DOCKER_TAG=${{ github.sha }}" >> .env

          git pull origin deploy

          docker-compose down
          docker-compose up -d

          docker image prune -a -f